function [PLOT] = plot_controls0
% Plotting controls for FE analysis

% Plotting flags for FE_plot
PLOT.plot = 1; % 1 = plot output
PLOT.fig = 1; % Figure number
PLOT.scale = 1; % Deformation scale
PLOT.undef = 1; % Plot undeformed shape
PLOT.def = 1; % Plot deformed shape
PLOT.force = 1; % Plot forces
PLOT.number = 0; % Plot node numbers
PLOT.triad = 1; % Plot triad
PLOT.els = [0 0 1 0]'; % Element types to plot [1 2 3 4];
PLOT.view = 2;

PLOT.plot_inc = true; % Plot each increment switch
PLOT.plot_iter = false; % Plot each iteration switch

% Analysis plot

% % % a = sprintf(['for i = 1:7\n',...
% % %     '    disp(i)\n',...
% % %     'end']);

PLOT.plot_shape = sprintf(['th = size(FEM.MODEL.theta,1);\n', ...
    'for i = 1:8\n', ...
    '    eps = FEM.EL((i - 1)*th + 1).el_in0.flex.e(1);\n', ...
    '    axial = FEM.EL((i - 1)*th + 1).el_in0.nodes(1).cords.axial;\n', ...
    '    f = interp1(axial(:,2),axial(:,1),eps);\n', ...
    '    FEM.OUT.cord_f(FEM.inc_count + 1,i) = f;\n', ...
    'end\n', ...
    'for i = 1:8\n', ...
    '    eps2 = FEM.EL((i - 1)*th + 1).el_in0.flex.e(2);\n', ...
    '    axial = FEM.EL((i - 1)*th + 1).el_in0.nodes(1).cords.axial;\n', ...
    '    f2 = interp1(axial(:,2),axial(:,1),eps2);\n', ...
    '    FEM.OUT.cord_f2(FEM.inc_count + 1,i) = f2;\n', ...
    'end\n']);

% PLOT.plot_shape = 'plot_inc(FEM);';

end

